server:
  port: 8080
  servlet:
    context-path: /travel/api
spring:
  application:
    name: Travel-Strategy-Api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel_strategy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Aa123456
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      location: /upload/tmp
      file-size-threshold: 5MB
      max-file-size: 20MB
  web:
    resources:
      static-locations: classpath:static/,file:${spring.servlet.multipart.location}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/com/mali/travelstrategy/mapper/xml/*Mapper.xml


#travel:
#  path:
#    upload: c:/data/upload